name: Deploy via CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Artifact
        run: zip -r myapp.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "./"
          DEST_DIR: "codedeploy/myapp"

      - name: Deploy with CodeDeploy
        uses: webfactory/aws-codedeploy-action@v0.3.1
        with:
          application-name: "my-react-app-deploy"
          deployment-group: "MyAppDeploymentGroup"
          deployment-config: "CodeDeployDefault.AllAtOnce"
          s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
          s3-key: "codedeploy/myapp/myapp.zip"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
